#!/bin/sh

cd "SVGViewTests"

function generateTest() {
    RES="// Generated by script-test-cases.sh\n\n"
    RES+="import XCTest\n"
    RES+="@testable import SVGView\n\n"
    RES+="class $2: BaseTestCase {\n\n"
    RES+="    override var dir: String {\n"
    RES+="        return \"$1\"\n"
    RES+="    }\n\n"

    REFS=$(find "w3c/$1/refs/" -type f -regex '.*\.ref$' | sort)

    for F in $REFS; do
        NAME="$(basename ${F%.*})"
        ARR=(${NAME//-/ })
        TEST_NAME=""
        for A in "${ARR[@]}"; do
            TEST_NAME+=$(printf "%s" "${A:0:1}" | tr '[:lower:]' '[:upper:]')${A:1}
        done
        RES+="    func test$TEST_NAME() {\n"
        RES+="        compareToReference(\"$NAME\")\n"
        RES+="    }\n\n"
    done

    RES+="}"

    echo "$RES" > ../SVGViewTests/$2.swift
}

generateTest "1.1F2" "SVG11Tests"
generateTest "1.2T" "SVG12Tests"
