#!/bin/sh

BASE_DIR="SVGViewTests"
DONE_FOLDER="w3c/1.2T/refs/"

cd $BASE_DIR

DONE=$(find "$DONE_FOLDER" -type f -regex '.*\.ref$' | sort)
DONE_COUNT=$(echo "$DONE" | wc -l | tr -d ' ')

RES="// Generated by script-test-cases.sh

import XCTest
@testable import SVGView

class SVG12Tests: XCTestCase {

    let testFolderName = \"TestOutputData\"\n\n"

for F in $DONE; do
    NAME="$(basename ${F%.*})"
    ARR=(${NAME//-/ })
    TEST_NAME=""
    for A in "${ARR[@]}"; do
        TEST_NAME+=$(printf "%s" "${A:0:1}" | tr '[:lower:]' '[:upper:]')${A:1}
    done
    RES+="    func test$TEST_NAME() {
        compareToReference(\"$NAME\")
    }\n\n"
done

RES+="}"

echo "$RES" > ../SVGViewTests/SVG12Tests.swift
