// Generated by script-test-cases.sh

import XCTest
@testable import SVGView

class SVG11Tests: BaseTestCase {

    override var dir: String {
        return "1.1F2"
    }

    func testColorProp01B() {
        compareToReference("color-prop-01-b")
    }

    func testColorProp02F() {
        compareToReference("color-prop-02-f")
    }

    func testColorProp03T() {
        compareToReference("color-prop-03-t")
    }

    func testColorProp04T() {
        compareToReference("color-prop-04-t")
    }

    func testColorProp05T() {
        compareToReference("color-prop-05-t")
    }

    func testCoordsCoord01T() {
        compareToReference("coords-coord-01-t")
    }

    func testCoordsCoord02T() {
        compareToReference("coords-coord-02-t")
    }

    func testCoordsTrans01B() {
        compareToReference("coords-trans-01-b")
    }

    func testCoordsTrans02T() {
        compareToReference("coords-trans-02-t")
    }

    func testCoordsTrans03T() {
        compareToReference("coords-trans-03-t")
    }

    func testCoordsTrans04T() {
        compareToReference("coords-trans-04-t")
    }

    func testCoordsTrans05T() {
        compareToReference("coords-trans-05-t")
    }

    func testCoordsTrans06T() {
        compareToReference("coords-trans-06-t")
    }

    func testCoordsTrans07T() {
        compareToReference("coords-trans-07-t")
    }

    func testCoordsTrans08T() {
        compareToReference("coords-trans-08-t")
    }

    func testCoordsTrans09T() {
        compareToReference("coords-trans-09-t")
    }

    func testCoordsTrans10F() {
        compareToReference("coords-trans-10-f")
    }

    func testCoordsTrans11F() {
        compareToReference("coords-trans-11-f")
    }

    func testCoordsTrans12F() {
        compareToReference("coords-trans-12-f")
    }

    func testCoordsTrans13F() {
        compareToReference("coords-trans-13-f")
    }

    func testCoordsTrans14F() {
        compareToReference("coords-trans-14-f")
    }

    func testCoordsTransformattr01F() {
        compareToReference("coords-transformattr-01-f")
    }

    func testCoordsTransformattr02F() {
        compareToReference("coords-transformattr-02-f")
    }

    func testCoordsTransformattr03F() {
        compareToReference("coords-transformattr-03-f")
    }

    func testCoordsTransformattr04F() {
        compareToReference("coords-transformattr-04-f")
    }

    func testCoordsTransformattr05F() {
        compareToReference("coords-transformattr-05-f")
    }

    func testCoordsUnits02B() {
        compareToReference("coords-units-02-b")
    }

    func testCoordsUnits03B() {
        compareToReference("coords-units-03-b")
    }

    func testMaskingOpacity01B() {
        compareToReference("masking-opacity-01-b")
    }

    func testPaintingControl02F() {
        compareToReference("painting-control-02-f")
    }

    func testPaintingControl03F() {
        compareToReference("painting-control-03-f")
    }

    func testPaintingFill01T() {
        compareToReference("painting-fill-01-t")
    }

    func testPaintingFill02T() {
        compareToReference("painting-fill-02-t")
    }

    func testPaintingFill03T() {
        compareToReference("painting-fill-03-t")
    }

    func testPaintingFill04T() {
        compareToReference("painting-fill-04-t")
    }

    func testPaintingFill05B() {
        compareToReference("painting-fill-05-b")
    }

    func testPaintingStroke01T() {
        compareToReference("painting-stroke-01-t")
    }

    func testPaintingStroke02T() {
        compareToReference("painting-stroke-02-t")
    }

    func testPaintingStroke03T() {
        compareToReference("painting-stroke-03-t")
    }

    func testPaintingStroke04T() {
        compareToReference("painting-stroke-04-t")
    }

    func testPaintingStroke05T() {
        compareToReference("painting-stroke-05-t")
    }

    func testPaintingStroke07T() {
        compareToReference("painting-stroke-07-t")
    }

    func testPaintingStroke08T() {
        compareToReference("painting-stroke-08-t")
    }

    func testPaintingStroke09T() {
        compareToReference("painting-stroke-09-t")
    }

    func testPathsData01T() {
        compareToReference("paths-data-01-t")
    }

    func testPathsData02T() {
        compareToReference("paths-data-02-t")
    }

    func testPathsData03F() {
        compareToReference("paths-data-03-f")
    }

    func testPathsData04T() {
        compareToReference("paths-data-04-t")
    }

    func testPathsData05T() {
        compareToReference("paths-data-05-t")
    }

    func testPathsData06T() {
        compareToReference("paths-data-06-t")
    }

    func testPathsData07T() {
        compareToReference("paths-data-07-t")
    }

    func testPathsData08T() {
        compareToReference("paths-data-08-t")
    }

    func testPathsData09T() {
        compareToReference("paths-data-09-t")
    }

    func testPathsData10T() {
        compareToReference("paths-data-10-t")
    }

    func testPathsData12T() {
        compareToReference("paths-data-12-t")
    }

    func testPathsData13T() {
        compareToReference("paths-data-13-t")
    }

    func testPathsData14T() {
        compareToReference("paths-data-14-t")
    }

    func testPathsData15T() {
        compareToReference("paths-data-15-t")
    }

    func testPathsData16T() {
        compareToReference("paths-data-16-t")
    }

    func testPathsData17F() {
        compareToReference("paths-data-17-f")
    }

    func testPathsData18F() {
        compareToReference("paths-data-18-f")
    }

    func testPathsData19F() {
        compareToReference("paths-data-19-f")
    }

    func testPathsData20F() {
        compareToReference("paths-data-20-f")
    }

    func testPserversGrad01B() {
        compareToReference("pservers-grad-01-b")
    }

    func testPserversGrad02B() {
        compareToReference("pservers-grad-02-b")
    }

    func testPserversGrad04B() {
        compareToReference("pservers-grad-04-b")
    }

    func testPserversGrad05B() {
        compareToReference("pservers-grad-05-b")
    }

    func testPserversGrad07B() {
        compareToReference("pservers-grad-07-b")
    }

    func testPserversGrad09B() {
        compareToReference("pservers-grad-09-b")
    }

    func testRenderElems01T() {
        compareToReference("render-elems-01-t")
    }

    func testRenderElems02T() {
        compareToReference("render-elems-02-t")
    }

    func testRenderElems03T() {
        compareToReference("render-elems-03-t")
    }

    func testShapesCircle01T() {
        compareToReference("shapes-circle-01-t")
    }

    func testShapesCircle02T() {
        compareToReference("shapes-circle-02-t")
    }

    func testShapesEllipse01T() {
        compareToReference("shapes-ellipse-01-t")
    }

    func testShapesEllipse02T() {
        compareToReference("shapes-ellipse-02-t")
    }

    func testShapesEllipse03F() {
        compareToReference("shapes-ellipse-03-f")
    }

    func testShapesGrammar01F() {
        compareToReference("shapes-grammar-01-f")
    }

    func testShapesIntro01T() {
        compareToReference("shapes-intro-01-t")
    }

    func testShapesLine01T() {
        compareToReference("shapes-line-01-t")
    }

    func testShapesLine02F() {
        compareToReference("shapes-line-02-f")
    }

    func testShapesPolygon01T() {
        compareToReference("shapes-polygon-01-t")
    }

    func testShapesPolygon02T() {
        compareToReference("shapes-polygon-02-t")
    }

    func testShapesPolygon03T() {
        compareToReference("shapes-polygon-03-t")
    }

    func testShapesPolyline01T() {
        compareToReference("shapes-polyline-01-t")
    }

    func testShapesPolyline02T() {
        compareToReference("shapes-polyline-02-t")
    }

    func testShapesRect02T() {
        compareToReference("shapes-rect-02-t")
    }

    func testShapesRect04F() {
        compareToReference("shapes-rect-04-f")
    }

    func testShapesRect05F() {
        compareToReference("shapes-rect-05-f")
    }

    func testShapesRect06F() {
        compareToReference("shapes-rect-06-f")
    }

    func testStructDefs01T() {
        compareToReference("struct-defs-01-t")
    }

    func testStructFrag01T() {
        compareToReference("struct-frag-01-t")
    }

    func testStructFrag06T() {
        compareToReference("struct-frag-06-t")
    }

    func testStructGroup01T() {
        compareToReference("struct-group-01-t")
    }

    func testStructImage01T() {
        compareToReference("struct-image-01-t")
    }

    func testStructImage04T() {
        compareToReference("struct-image-04-t")
    }

    func testStructUse03T() {
        compareToReference("struct-use-03-t")
    }

    func testStylingClass01F() {
        compareToReference("styling-class-01-f")
    }

    func testStylingCss01B() {
        compareToReference("styling-css-01-b")
    }

    func testStylingPres01T() {
        compareToReference("styling-pres-01-t")
    }

    func testTypesBasic01F() {
        compareToReference("types-basic-01-f")
    }

}
