// Generated by script-test-cases.sh

import XCTest
@testable import SVGView

class SVG11Tests: BaseTestCase {

    override var dir: String {
        return "1.1F2"
    }

    func testColorProp02F() {
        compareToReference("color-prop-02-f")
    }

    func testColorProp03T() {
        compareToReference("color-prop-03-t")
    }

    func testCoordsCoord01T() {
        compareToReference("coords-coord-01-t")
    }

    func testCoordsTrans01B() {
        compareToReference("coords-trans-01-b")
    }

    func testCoordsTrans02T() {
        compareToReference("coords-trans-02-t")
    }

    func testCoordsTrans03T() {
        compareToReference("coords-trans-03-t")
    }

    func testCoordsTrans04T() {
        compareToReference("coords-trans-04-t")
    }

    func testCoordsTrans05T() {
        compareToReference("coords-trans-05-t")
    }

    func testCoordsTrans06T() {
        compareToReference("coords-trans-06-t")
    }

    func testCoordsTrans07T() {
        compareToReference("coords-trans-07-t")
    }

    func testCoordsTrans08T() {
        compareToReference("coords-trans-08-t")
    }

    func testCoordsTrans09T() {
        compareToReference("coords-trans-09-t")
    }

    func testCoordsTransformattr01F() {
        compareToReference("coords-transformattr-01-f")
    }

    func testCoordsTransformattr02F() {
        compareToReference("coords-transformattr-02-f")
    }

    func testPaintingControl03F() {
        compareToReference("painting-control-03-f")
    }

    func testPaintingFill01T() {
        compareToReference("painting-fill-01-t")
    }

    func testPaintingFill04T() {
        compareToReference("painting-fill-04-t")
    }

    func testPaintingFill05B() {
        compareToReference("painting-fill-05-b")
    }

    func testPaintingStroke01T() {
        compareToReference("painting-stroke-01-t")
    }

    func testPaintingStroke04T() {
        compareToReference("painting-stroke-04-t")
    }

    func testPaintingStroke07T() {
        compareToReference("painting-stroke-07-t")
    }

    func testPathsData01T() {
        compareToReference("paths-data-01-t")
    }

    func testPathsData02T() {
        compareToReference("paths-data-02-t")
    }

    func testPathsData06T() {
        compareToReference("paths-data-06-t")
    }

    func testPathsData07T() {
        compareToReference("paths-data-07-t")
    }

    func testPathsData12T() {
        compareToReference("paths-data-12-t")
    }

    func testPathsData13T() {
        compareToReference("paths-data-13-t")
    }

    func testPathsData15T() {
        compareToReference("paths-data-15-t")
    }

    func testPathsData17F() {
        compareToReference("paths-data-17-f")
    }

    func testPathsData18F() {
        compareToReference("paths-data-18-f")
    }

    func testPathsData19F() {
        compareToReference("paths-data-19-f")
    }

    func testPathsData20F() {
        compareToReference("paths-data-20-f")
    }

    func testRenderElems01T() {
        compareToReference("render-elems-01-t")
    }

    func testRenderElems02T() {
        compareToReference("render-elems-02-t")
    }

    func testRenderElems03T() {
        compareToReference("render-elems-03-t")
    }

    func testStructDefs01T() {
        compareToReference("struct-defs-01-t")
    }

    func testStructFrag01T() {
        compareToReference("struct-frag-01-t")
    }

    func testStructFrag06T() {
        compareToReference("struct-frag-06-t")
    }

    func testStructGroup01T() {
        compareToReference("struct-group-01-t")
    }

    func testStructUse03T() {
        compareToReference("struct-use-03-t")
    }

    func testTypesBasic01F() {
        compareToReference("types-basic-01-f")
    }

}
