// Generated by script-test-cases.sh

import XCTest
@testable import SVGView

class SVG11Tests: BaseTestCase {

    override var dir: String {
        return "1.1F2"
    }

    func testColorProp02F() {
        compareToReference("color-prop-02-f")
    }

    func testColorProp03T() {
        compareToReference("color-prop-03-t")
    }

    func testCoordsCoord01T() {
        compareToReference("coords-coord-01-t")
    }

    func testCoordsTrans01B() {
        compareToReference("coords-trans-01-b")
    }

    func testCoordsTrans02T() {
        compareToReference("coords-trans-02-t")
    }

    func testCoordsTrans03T() {
        compareToReference("coords-trans-03-t")
    }

    func testCoordsTrans04T() {
        compareToReference("coords-trans-04-t")
    }

    func testCoordsTrans05T() {
        compareToReference("coords-trans-05-t")
    }

    func testCoordsTrans06T() {
        compareToReference("coords-trans-06-t")
    }

    func testCoordsTrans07T() {
        compareToReference("coords-trans-07-t")
    }

    func testCoordsTrans08T() {
        compareToReference("coords-trans-08-t")
    }

    func testCoordsTrans09T() {
        compareToReference("coords-trans-09-t")
    }

}
