// Generated by script-test-cases.sh

import XCTest
@testable import SVGView

class SVG12Tests: BaseTestCase {

    override var dir: String {
        return "1.2T"
    }

    func testCoordsTrans01T() {
        compareToReference("coords-trans-01-t")
    }

    func testCoordsTrans02T() {
        compareToReference("coords-trans-02-t")
    }

    func testCoordsTrans03T() {
        compareToReference("coords-trans-03-t")
    }

    func testCoordsTrans04T() {
        compareToReference("coords-trans-04-t")
    }

    func testCoordsTrans05T() {
        compareToReference("coords-trans-05-t")
    }

    func testCoordsTrans06T() {
        compareToReference("coords-trans-06-t")
    }

    func testCoordsTrans07T() {
        compareToReference("coords-trans-07-t")
    }

    func testCoordsTrans08T() {
        compareToReference("coords-trans-08-t")
    }

    func testCoordsTrans09T() {
        compareToReference("coords-trans-09-t")
    }

    func testPaintColor03T() {
        compareToReference("paint-color-03-t")
    }

    func testPaintColor201T() {
        compareToReference("paint-color-201-t")
    }

    func testPaintFill04T() {
        compareToReference("paint-fill-04-t")
    }
  
    func testPaintFill06T() {
        compareToReference("paint-fill-06-t")
    }

    func testPaintStroke01T() {
        compareToReference("paint-stroke-01-t")
    }

    func testPathsData01T() {
        compareToReference("paths-data-01-t")
    }

    func testPathsData02T() {
        compareToReference("paths-data-02-t")
    }

    func testRenderElems01T() {
        compareToReference("render-elems-01-t")
    }

    func testRenderElems02T() {
        compareToReference("render-elems-02-t")
    }

    func testRenderElems03T() {
        compareToReference("render-elems-03-t")
    }

    func testShapesCircle01T() {
        compareToReference("shapes-circle-01-t")
    }

    func testShapesEllipse01T() {
        compareToReference("shapes-ellipse-01-t")
    }

    func testShapesLine01T() {
        compareToReference("shapes-line-01-t")
    }

    func testShapesPolygon01T() {
        compareToReference("shapes-polygon-01-t")
    }

    func testShapesPolyline01T() {
        compareToReference("shapes-polyline-01-t")
    }

    func testShapesRect02T() {
        compareToReference("shapes-rect-02-t")
    }

    func testStructDefs01T() {
        compareToReference("struct-defs-01-t")
    }

    func testStructFrag01T() {
        compareToReference("struct-frag-01-t")
    }

    func testStructUse03T() {
        compareToReference("struct-use-03-t")
    }

}
